/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package CSU;

import GraphicElements.Rectangle;
import GraphicElements.ThickArrow;
import Utility.Frame.Status;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;

/**
 *
 * @author Istrac
 */
public class FlowStatus extends javax.swing.JPanel {

    private final Rectangle[] rectangles;
    private final ThickArrow[] thickArrows;
    private final String[] errdescword, finedescword;
    private final String[] names;

    /**
     * Creates new form FlowStatus
     */
    public FlowStatus() {
        initComponents();
        rectangles = new Rectangle[16];
        thickArrows = new ThickArrow[8];
        int index = 0;

        names = new String[]{"", "ANTENNA/:DUMMY:LOAD", "MODULATOR:MAINS", "HV",  "PULSE:WIDTH &:PRF", " MODULATION:", "RF", " TX: RADIATION:"};//0
        finedescword = new String[]{"REMOTE", "", "", " ON", " ON", "ON", " ON", "ON"};
        errdescword = new String[]{"LOCAL", "", "", " OFF", " OFF", " OFF", " OFF", " OFF"};
        for (int i = 0; i < 5; i++) {
            rectangles[index] = new Rectangle("", 6 + 20 * i, 10, 6, 12);
            rectangles[index].setRounded(false);
            rectangles[index].label.setFonttype(Font.BOLD);
            rectangles[index].label.setfontSize(12);
            rectangles[index].setTextanchor(Rectangle.LEFT);
            index++;
        }
        for (int i = 5; i < 8; i++) {
            rectangles[index] = new Rectangle("", 6 + 20 * (i - 5), 55, 6, 12);
            rectangles[index].setRounded(false);
            rectangles[index].label.setFonttype(Font.BOLD);
            rectangles[index].label.setfontSize(12);
            rectangles[index].setTextanchor(Rectangle.LEFT);
            index++;
        }
        for (int i = 0; i < 5; i++) {
            rectangles[index] = new Rectangle(names[i], 8 + 20 * i, 15, 10, 14);
            rectangles[index].setRounded(true);
            rectangles[index].setFillcolor(Color.WHITE);
            rectangles[index].label.setFonttype(Font.BOLD);
            rectangles[index].label.setfontSize(12);

            index++;
        }
        for (int i = 5; i < 8; i++) {
            rectangles[index] = new Rectangle(names[i], 8 + 20 * (i - 5), 60, 10, 14);
            rectangles[index].setRounded(true);
            rectangles[index].setFillcolor(Color.WHITE);
            rectangles[index].label.setFonttype(Font.BOLD);
            rectangles[index].label.setfontSize(12);
            index++;
        }

        for (int i = 0; i < 7; i++) {
            Point gf = rectangles[i].getContactPoint(Rectangle.RIGHT, 0.2);
            thickArrows[i] = new ThickArrow(gf.x + 4, gf.y, 3, 2);
            thickArrows[i].setColor(Color.LIGHT_GRAY);
        }
        Point gf = rectangles[5].getContactPoint(Rectangle.LEFT, 0.2);
        thickArrows[7] = new ThickArrow(gf.x - 5, gf.y, 3, 2);
        thickArrows[7].setColor(Color.LIGHT_GRAY);
        for(int i=0;i<2;i++){
            setStatus(i,Status.FINE);
        }
        for(int i=2;i<8;i++){
            setStatus(i,Status.ERROR);
        }
    }

    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        //setBackground(colors[BACKGROUND]);
        Graphics2D g2d = (Graphics2D) g;
        Dimension d = this.getSize();
        double xfactor = d.width / 100.0;
        double yfactor = d.height / 100.0;
        for (int i = 0; i < 16; i++) {
            rectangles[i].update(xfactor, yfactor);
            rectangles[i].draw(g2d);
        }
        for (int i = 0; i < 8; i++) {
            this.thickArrows[i].update(xfactor, yfactor);
            this.thickArrows[i].draw(g2d);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(0, 0));
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void setStatus(int comp, int status) {
        switch (status) {
            case Status.FINE:
                rectangles[comp].setFillcolor(Color.GREEN);
                rectangles[comp].settext("OK: : ");
                rectangles[comp+8].settext(names[comp]+finedescword[comp]);
                break;
            case Status.ERROR:
                rectangles[comp].setFillcolor(Color.RED);
                rectangles[comp].settext("NOT OK: : ");
                rectangles[comp+8].settext(names[comp]+errdescword[comp]);
                break;
                default:
                    ;
        }
        repaint();
    }
}
