/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package CSU;

import GraphicElements.MyButton;
import GraphicElements.PSpace;
import java.awt.GridBagConstraints;

/**
 *
 * @author Istrac
 */
public class MonitoringSelectionPanel extends javax.swing.JPanel {
public MyButton[] selectButtons;

    /**
     * Creates new form monitoringPanel
     */
    public MonitoringSelectionPanel() {
        initComponents();
        String[] names=new String[]{"FLOW:STATUS","ANALOG:MONITORING","INTERLOCK:DISPLAY","INTERLOCK:CONFIG","RF DETECTOR:CAL TABLE","TRIGGER:CONFIG"};        
        selectButtons = new MyButton[8];
        
        GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();

        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 1;
        gridBagConstraints.gridwidth = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.weighty = 0.33;
        for(int i=0;i<6;i++){
            gridBagConstraints.gridx = i%3;
            gridBagConstraints.gridy = i/3;
            selectButtons[i]=new MyButton(names[i]);
            selectButtons[i].setFontSize(12);
            PSpace sp=new PSpace(selectButtons[i],0.25,0.3,0.25,0.3);
            add(sp,gridBagConstraints);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
